app/models/__init__.py
from .user import User
from .post import Post
from .pagination import PaginatedAPIMixin

app/models/pagination.py
from flask import url_for

class PaginatedAPIMixin(object):
    @staticmethod
    def to_collection_dict(query, page, per_page, endpoint, **kwargs):
        resources = query.paginate(page, per_page, False)
        data = {
            'items': [item.to_dict() for item in resources.items],
            '_meta': {
                'page': page,
                'per_page': per_page,
                'total_pages': resources.pages,
                'total_items': resources.total
            },
            '_links': {
                'self': url_for(endpoint, page=page, per_page=per_page,
                                **kwargs),
                'next': url_for(endpoint, page=page + 1, per_page=per_page,
                                **kwargs) if resources.has_next else None,
                'prev': url_for(endpoint, page=page - 1, per_page=per_page,
                                **kwargs) if resources.has_prev else None
            }
        }

        return data

app/models/post.py
from datetime import datetime
from app import db

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(120))
    body = db.Column(db.String(255))
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return '<Post {}>'.format(self.body)

    def add(self):
        try:
            db.session.add(self)
            db.session.commit()
            return self
        except:
            return 0

    def all(self):
        return self.query.all()

app/models/user.py
from app import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from app import login
from hashlib import md5
from datetime import datetime
from app.models.post import Post
from app.models.pagination import PaginatedAPIMixin
from flask import url_for

@login.user_loader
def load_user(id):
    return User.query.get(int(id))

class User(PaginatedAPIMixin, UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password = db.Column(db.String(120))
    about_me = db.Column(db.String(160))
    last_seen = db.Column(db.DateTime, default=datetime.utcnow)
    posts = db.relationship('Post', backref='author', lazy='dynamic')

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def add(self):
        try:
            db.session.add(self)
            db.session.commit()
            return self
        except:
            return 0
    
    def avatar(self, size):
        digest = md5(self.email.lower().encode('utf-8')).hexdigest()
        return 'https://www.gravatar.com/avatar/{}?d=identicon&s={}'.format(digest, size)

    def own_post(self):
        return Post.query.filter_by(user_id=self.id)

    def to_dict(self, include_email=False):
        data = {
            'id': self.id,
            'username': self.username,
            'last_seen': self.last_seen,
            'about_me': self.about_me,
            '_links': {
                'self': url_for('api.get_user', id=self.id),
                'avatar': self.avatar(128)
            }
        }

        if include_email:
            data['email']: self.email

        return data

    def from_dict(self, data, new_user=False):
        for field in ['username', 'email', 'about_me']:
            if field in data:
                setattr(self, field, data[field])

        if new_user and 'password' in data:
            self.set_password(data['password'])

app/blog/forms/post.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, StringField, SubmitField
from wtforms.validators import DataRequired, Length

class Post(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(min=1, max=120)])
    body = TextAreaField('Your body here.. ', validators=[DataRequired(), Length(min=1, max=255)])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask 
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from logging.handlers import RotatingFileHandler
import os, logging
from flask_bootstrap import Bootstrap

app = Flask(__name__)
app.config.from_object(Config)
db = SQLAlchemy(app)
migrate = Migrate(app, db)
login = LoginManager(app)
login.login_view = 'auth.login'
bootstrap = Bootstrap(app)

from app.errors import bp as error_bp
app.register_blueprint(error_bp)

from app.auth import bp as auth_bp
app.register_blueprint(auth_bp, url_prefix='/auth')

from app.blog import bp as blog_bp
app.register_blueprint(blog_bp, url_prefix='/blog')

from app.main import bp as main_bp
app.register_blueprint(main_bp)

from app.api import bp as api_bp
app.register_blueprint(api_bp)

if not os.path.exists('logs'):
    os.mkdir('logs')
file_handler = RotatingFileHandler('logs/log.log', maxBytes=10240, backupCount=10)
file_handler.setFormatter(logging.Formatter('%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'))
file_handler.setLevel(logging.INFO)
app.logger.info('blog start')

from app import models

app/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__)

from app.api import users, errors, token

app/blog/__init__.py
from flask import Blueprint

bp = Blueprint('blog', __name__)

from app.blog import forms, routes

app/blog/routes.py
from app import db
from app.blog import bp
from flask import render_template, flash, url_for, redirect
from app.blog.forms.post import Post as PostForm
from flask_login import current_user, login_required
from app.models.post import Post
from datetime import datetime

@bp.route('/')
@bp.route('/index')
@login_required
def index():
    post = Post()
    posts = post.all()
    return render_template('blog/index.html', title='Index', posts=posts)

@bp.route('/new_post', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, body=form.body.data, author=current_user)
        if post.add():
            flash('post added')
        else:
            flash('Sorry something went wrong')
        return redirect(url_for('blog.index'))
    return render_template("blog/new_post.html", title="Add New Post", form=form)

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from app import db
from app.main import bp
from flask import render_template, flash, url_for, redirect
from flask_login import current_user, login_required
from datetime import datetime

@bp.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()

@bp.route('/')
@bp.route('/index')
@login_required
def index():
    return render_template('index.html', title='Index')

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{% block title %}
    {% if title %}
    Blog - {{ title }}
    {% else %}
    Welcome to Blog
    {% endif %}
{% endblock %}

{% block navbar %}
    Blog : <a href="{{ url_for('main.index') }}">Home</a> | 
    {% if current_user.is_anonymous %}
        <a href="{{ url_for('auth.login') }}">Login</a>
    {% else %}
        <a href="{{ url_for('blog.index') }}">Blog</a> | 
        <a href="{{ url_for('auth.user', username=current_user.username) }}">Profile</a> |
        <a href="{{ url_for('auth.logout') }}">Logout</a>
    {% endif %}
{% endblock %}
    
{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

app/templates/blog/_post.html
<table>
    <tr valign="top">
        <td><img src="{{ post.author.avatar(36) }}"></td>
        <td>{{ post.author.username }} <br>{{ post.body }}</td>
    </tr>
</table>

app/templates/blog/index.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Post</h1>
    <a href="{{ url_for('blog.new_post') }}">new Post</a>
    {% for post in posts %}
    <p>
    {{ post.title }} by {{ post.author.username }} says: <b>{{ post.body }}</b>
    </p>
    {% endfor %}
{% endblock %}

app/templates/blog/new_post.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Create Post</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.title.label }}<br>
            {{ form.title(size=120) }}<br>
            {% for error in form.title.errors %}
            <span style="color: #ff0102;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.body.label }}<br>
            {{ form.body(cols=50, rows=4) }}<br>
            {% for error in form.body.errors %}
            <span style="color: #ff0102;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Hello</h1>
    <p>Hello, {{ current_user.username }}</p>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Sign In</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}
        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>{{ form.submit() }}</p>
        <p><a href="{{ url_for('register') }}">Register Now!</a></p>
    </form>
{% endblock %}

app/templates/user.html
{% extends "base.html" %}

{% block app_content %}
    <table>
        <tr valign="top">
            <td><img src="{{ user.avatar(128) }}"></td>
            <td>
                <h1>User: {{ user.username }}</h1>
                {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
                {% if user.last_seen %}<p>Last seen on: {{ user.last_seen }}</p>{% endif %}
            </td>
            
        </tr>
    </table>
    {% if user == current_user %}
        <p><a href="{{ url_for('edit_profile') }}">Edit your profile</a></p>
    {% endif %}
    <hr>
    {% for post in posts %}
        {% include '_post.html' %}
    {% endfor %}
{% endblock %}